spring:
  application:
    name: Artisan-dor
  datasource:
    url: jdbc:postgresql://dpg-cq8h4vmehbks738k20v0-a.frankfurt-postgres.render.com:5432/artisan
    username: artisan_user
    password: oLkHJfjnLngSyJeqCHE6rMBOVIA3nhNT
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.example.com  # Replace with your SMTP server host
    port: 587               # Replace with your SMTP server port
    username: your-email@example.com
    password: your-email-password
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true

logging:
  level:
    org:
      hibernate:
        SQL: debug